name: Build Module ZIP

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create ZIP Package
        run: |
          zip -r swapspeakers.zip . -x "*.git*" ".github/*" "README.md" ".gitignore"

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: swapspeakers.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
